### Numpy Library
It is used to create multi dimentional matrix creation. it contains different array operations. It is used  in dtaa science

In [2]:
## To download the Numpy library = pip install numpy
 

### Array 
It is basically one type data structure is similar to list data structure. But main differenece is here it only contain similar data type inside in it

In [3]:
# Importing Numpy library as np 
import numpy as np 

In [4]:
my_list=[23,445,43]
arr=np.array(my_list)
print('Values of array is',arr)
print('The datatype of arr',type(arr))  # This is one dimention array 


Values of array is [ 23 445  43]
The datatype of arr <class 'numpy.ndarray'>


In [5]:
# To check the dimention we use shape function
arr.shape

(3,)

In [6]:
### Creation of two dimention array 
a=[234,242,31242,3,4]
b=[24,3412,4443434,5,4]
c=[34,32414,5314,4,4]
all_combine=np.array([a,b,c])
print('two dimention array is \n',all_combine)


two dimention array is 
 [[    234     242   31242       3       4]
 [     24    3412 4443434       5       4]
 [     34   32414    5314       4       4]]


In [7]:
all_combine

array([[    234,     242,   31242,       3,       4],
       [     24,    3412, 4443434,       5,       4],
       [     34,   32414,    5314,       4,       4]])

In [8]:
all_combine.shape

(3, 5)

In [9]:
all_combine.reshape(5,3) # here i convert matrix that is 3*5 to 5*3

array([[    234,     242,   31242],
       [      3,       4,      24],
       [   3412, 4443434,       5],
       [      4,      34,   32414],
       [   5314,       4,       4]])

### Idexing of the array 

In [10]:
new_array=np.array([2,3,2,334,3,33])
print(new_array)
print(new_array[3])

[  2   3   2 334   3  33]
334


In [11]:
# in two dimention
all_combine=np.array([a,b,c])
print(all_combine[:,:])  # This means we have to print all  the rows and columns.

[[    234     242   31242       3       4]
 [     24    3412 4443434       5       4]
 [     34   32414    5314       4       4]]


In [12]:
all_combine[0:2,0:2]# Printing  the first two rows and first two cloumns element 

array([[ 234,  242],
       [  24, 3412]])

In [13]:
all_combine[1:,1:3]

array([[   3412, 4443434],
       [  32414,    5314]])

### Inbuilt Function

In [16]:
arr11=np.arange(0,10,2)# Start stop and step 
print(arr11)

[0 2 4 6 8]


In [17]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
# copy function in array 
arr11[3:]=100
print(arr11)

[  0   2   4 100 100]


In [22]:
# Copy function and  broadcasting 
arr_copied_version=arr11  # When we assign one array into another array that time its connected each other. Like if we change anything one array it will reflect another array to 
arr_copied_version[3:]=500
print(arr_copied_version)
print(arr11)

[  0   2   4 500 500]
[  0   2   4 500 500]


In [27]:
print('The before arr11 values is ',arr11)
arr_copy=arr11.copy()
print('The new copied array values is ',arr_copy)
# Now we are changing in the arr11 array and let's see what change is there
arr11[3:]=2405

print('\nThe before arr11 values is ',arr11)
print('The new copied array values is ',arr_copy)


The before arr11 values is  [  0   2   4 500 500]
The new copied array values is  [  0   2   4 500 500]

The before arr11 values is  [   0    2    4 2405 2405]
The new copied array values is  [  0   2   4 500 500]


In [32]:
# Create arrays and reshape 
b=np.arange(15,25).reshape(5,2)
a=np.arange(0,10).reshape(5,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


In [34]:
# Different Mathematical Operation
print(a+b)
print(a-b)
print(a*b)


[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]]
[[-15 -15]
 [-15 -15]
 [-15 -15]
 [-15 -15]
 [-15 -15]]
[[  0  16]
 [ 34  54]
 [ 76 100]
 [126 154]
 [184 216]]


In [36]:
# Creating ones and zeros array 
aa=np.ones(4,dtype=int)
print(aa)
np.ones((2,5),dtype=int)

[1 1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
# Random distribution 
a=np.random.rand(3,3)
print(a)

[[0.86323679 0.0607643  0.46452143]
 [0.71618435 0.78607375 0.49099927]
 [0.43889612 0.16405581 0.90198927]]


In [40]:
arr_exp=np.random.randn(10)
print(arr_exp)

[ 0.33254743  0.10444169 -1.11242294  0.87848373 -2.15804924 -0.54582493
 -0.90047027 -0.61716866  0.66042949 -0.35600764]


In [42]:
np.random.randn(1,6)

array([[-1.43820276,  0.22742991, -0.11330941,  0.02595675,  0.06152943,
        -0.70972507]])

In [43]:
np.random.randint(1,100,5)

array([88, 15, 78,  2, 57])